### ISSUE TITLE
Hello, can I obtain the model file you used in this project?

### ISSUE THREAD

**Issue by ConcealGeek** [CCP101/CCP101#1]
Hello, can I obtain the model file you used in this project?
My local device is training very slowly, so if possible, I would greatly appreciate it.

https://github.com/CCP101/ML_2021/tree/master

**Comment by CCP101** [comment]
你好，我看到你在个人资料上是在杭州，那我直接用中文回答了
这个项目是两年前跑的了，模型文件应该还在我可以找一下
但有个问题，这个项目我也是拿自己笔记本上的显卡跑的，所以为了结果展示只训练了1000个中文字的识别，没有训练全部的中文字符识别，你看下还需要么

**Comment by ConcealGeek** [comment]
> 你好，我看到你在个人资料上是在杭州，那我直接用中文回答了 这个项目是两年前跑的了，模型文件应该还在我可以找一下 但有个问题，这个项目我也是拿自己笔记本上的显卡跑的，所以为了结果展示只训练了1000个中文字的识别，没有训练全部的中文字符识别，你看下还需要么

需要的老板，十分感谢

**Comment by CCP101** [comment]
你好，不好意思因为文件太大我网盘和本地留存的文件都删掉了
我这里只能建议你使用AutoDL AI算力云重新跑一遍了，我有些实验用这个平台跑也不是特别贵
如果代码方面有问题可以问我，我很乐意为你解答
目前AI界大趋势还是pytorch，当时是因为我在本科阶段用的TF1，TF2又刚出所以用的TF2来写代码，建议你可以找找pytorch版本的

**Comment by ConcealGeek** [comment]
> 你好，不好意思因为文件太大我网盘和本地留存的文件都删掉了 我这里只能建议你使用AutoDL AI算力云重新跑一遍了，我有些实验用这个平台跑也不是特别贵 如果代码方面有问题可以问我，我很乐意为你解答 目前AI界大趋势还是pytorch，当时是因为我在本科阶段用的TF1，TF2又刚出所以用的TF2来写代码，建议你可以找找pytorch版本的

ok，感谢你的建议我去试试

**Comment by ConcealGeek** [comment]
> 你好，不好意思因为文件太大我网盘和本地留存的文件都删掉了 我这里只能建议你使用AutoDL AI算力云重新跑一遍了，我有些实验用这个平台跑也不是特别贵 如果代码方面有问题可以问我，我很乐意为你解答 目前AI界大趋势还是pytorch，当时是因为我在本科阶段用的TF1，TF2又刚出所以用的TF2来写代码，建议你可以找找pytorch版本的

你好，我有几个问题想问你一下，发了一封邮件给你，期待你的回复
